// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHdXloyph3FTXzNT9onMLuRcT5KMvWqIg',
    appId: '1:924795589763:web:0c77f134d10cfebb6337b6',
    messagingSenderId: '924795589763',
    projectId: 'nithlostnfound',
    authDomain: 'nithlostnfound.firebaseapp.com',
    storageBucket: 'nithlostnfound.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNmZ6sHUiExKg82yRRf4M9h3JTSs3QhT4',
    appId: '1:924795589763:android:13acd61ad9f3d9456337b6',
    messagingSenderId: '924795589763',
    projectId: 'nithlostnfound',
    storageBucket: 'nithlostnfound.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4yWF9kd-JEYw08_WgAnwh9yHTRKYcvjI',
    appId: '1:924795589763:ios:57921f26b7c011ef6337b6',
    messagingSenderId: '924795589763',
    projectId: 'nithlostnfound',
    storageBucket: 'nithlostnfound.appspot.com',
    iosBundleId: 'com.example.lostnfound',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4yWF9kd-JEYw08_WgAnwh9yHTRKYcvjI',
    appId: '1:924795589763:ios:57921f26b7c011ef6337b6',
    messagingSenderId: '924795589763',
    projectId: 'nithlostnfound',
    storageBucket: 'nithlostnfound.appspot.com',
    iosBundleId: 'com.example.lostnfound',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHdXloyph3FTXzNT9onMLuRcT5KMvWqIg',
    appId: '1:924795589763:web:f0b8d483ac6037586337b6',
    messagingSenderId: '924795589763',
    projectId: 'nithlostnfound',
    authDomain: 'nithlostnfound.firebaseapp.com',
    storageBucket: 'nithlostnfound.appspot.com',
  );
}
