class AppDropdownMenu {
  final List<String> itemTypes = [
    'Item Type',
    'ID Card',
    'Book',
    'Mobile Phone',
    'Laptop',
    'Earbuds',
    'Mobile Charger',
    'Laptop Charger',
    'Specs',
    'Watch',
    'Jewelry',
    'Jackets/Coats',
    'Shoes',
    'Umbrella',
    'Keys',
    'Electronics',
    'Water bottle',
    'Clothing',
    'Books',
    'Other',
  ];
  final List<String> locations = [
    'Campus',
    'Boys Hostel',
    'Girls Hostel',
    'Department',
    'Library',
    'Computer Center',
    'Lecture Hall',
    'New LH',
    'Auditorium',
    'OAT',
    'Ground',
    'Central Gym',
    'SP',
    '4 H',
    'Verka',
    'Amul',
    'Admin Block',
    'Central Block',
    'Food Court',
    'Nasecafe DBH',
    'GATE 1',
    'GATE 2',
    'Temple',
    'SAC',
  ];
  static const List<String> boysHostels = [
    'KBH',
    'NBH',
    'UBH',
    'VBH',
    'DBH',
    'Himadri',
    'Himgiri'
  ];
  static const List<String> girlsHostels = [
    'AGH',
    'New AGH',
    'PGH',
    'MMH',
    'Satpura',
  ];
  static const List<String> departments = [
    'CSE',
    'Electrical',
    'Civil',
    'ECE',
    'MNC',
    'EP',
    'Chemical',
    'Mechanical',
    'Architecture',
    'MS',
  ];
}
